server:
    port: 8084
   

spring:
   application:
      name: IGRSQUERY-SERVICE-PREETI
   main:
      allow-bean-definition-overriding: true
      allow-circular-references : true
      
   datasource:
      url: jdbc:mysql://localhost:3306/igrsquery
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      
   jpa:
      hibernate:
         ddl-auto: update
         naming:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      show-sql: true
      properties:
         hibernate:
             dialect: org.hibernate.dialect.MySQL5Dialect
  
   ribbon: 
      connectTimeout: 3000
      readTimeout: 60000   
                  
    
   cloud:
      config:
            enabled: true
   
   config:
    import:
      configserver:http://192.168.1.60:8085
 

eureka:
   instance:
      prefer-ip-address: false
   client:
      fetch-registry: true
      register-with-eureka: true
      serviceUrl: 
         defaultZone: http://Ankush:Neel123@192.168.1.60:8761/eureka 
         
         
management: 
   health:
      circuitbreakers:
         enabled: true
   endpoints:
      web:
         exposure:
            include: '*'
   endpoint:
      health:
         show-details: always
         
         
         
resilience4j:
   circuitbreaker: 
      instances:
         userIdByPrincipalBreaker_Query_User:
            registerHealthIndicator: true
            eventConsumerBufferSize: 10
            failureRateThreshold: 50
            minimumNumberOfCalls: 5
            automaticTransitionFromOpenToHalfOpenEnabled: true
            waitDurationInOpenState: 6s
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowSize: 10
            slidingWindowType: COUNT_BASED
            
            
   retry:
      instances:
         userIdByPrincipalRetry_Query_User:
            max-attempts: 3
            wait-duration: 5s
            
            
   
   rateLimiter:
      instances:
         userIdByPrincipalLimiter_Query_User:
            timeoutDuration: 2s
            limitRefreshPeriod: 4s
            limitForPeriod: 2
            
            
            

 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
      
         